language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-django111
    - python: 3.4
      env: TOXENV=py34-django111
    - python: 3.5
      env: TOXENV=py35-django111
    - python: 3.6
      env: TOXENV=py36-django111
    - python: 3.7
      env: TOXENV=py37-django111
      dist: xenial
      sudo: true
    - env: TOXENV=flake8
    - env: TOXENV=isort

before_install:
  - export DJANGO_SETTINGS_MODULE=tests.settings

install:
  - pip install tox

script:
  - tox -v
